version: "3"
services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:alpine
    command:
      - 'redis-server'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 2'
      - '--maxmemory 100000mb'
      - '--maxmemory-policy noeviction'
      - '--save 60 5'
    # volumes:
    #   - redis:/data
